### ISSUE TITLE
Merge: location of nodes

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#40]
Sometimes the location of the nodes after merging is off, especially if the merged nodes are at different x-location

**Comment by Bram28** [comment]
It's still a bit off:

![merge bug](https://cloud.githubusercontent.com/assets/2414519/6043449/3fdb440e-ac5a-11e4-89ba-59e7f58fcfff.png)

I would like the distance between each node to be the same, i.e. the merged node should be closer to the nodes it came from. That way, no matter how many branches you have, the board nodes and the transition nodes will always line up in the same columns.

**Comment by samuelyuan** [comment]
I just pushed a commit that should make the distances between nodes equal.
3368551b02e1d3dcdc37ab39da32c96e214ad044

**Comment by Bram28** [comment]
Hi Sam,

So I asked and we have to go through URP again to get you paid some of that money, but unfortunately you cannot do 2 URP’s … so you’ll have to decide: would you prefer getting paid (in which case you’ll need to drop the 2 credit URP), or do you want to stick to earning those 2 credits? Also: since I was offered $1200 total, it would only be $300 if we split this between you, Avi, Aaron, and Mitch.  So please let me know what you want to do. Thanks!



Bram
