### ISSUE TITLE
Nurikabe: Continue Black and Continue White

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#41]
Continue Black and White should be able to continue several cells, not just one at a time. Also: maybe combine the Continue White and Continue Numberless Region as in: Continue White ... as long as it needs more white ... for which there are these two separate reasons ... but both are fairly obvious ... so just one rule will do ... also for symmetry sake with Continue Black

**Comment by mmellone** [comment]
Solved with black and white bottle neck rules.

**Comment by Bram28** [comment]
Excellent!
