### ISSUE TITLE
Nurikabe: Extend Black Between Regions

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#46]
Extend this rule so that the user is allowed to place a black between two white regions when:

1. One region contains a number
2. The other region does not
3. Placing a white between the regions would create one region with a size greater than the number

**Comment by mmellone** [comment]
Fixed a bug with this. Appears to work well now.
e4a8eec4da92763ed24e7b8bc06309534a442400

**Comment by Bram28** [comment]
Great, thanks!
