### ISSUE TITLE
Nurikabe: Bottle Neck rule for Black

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#48]
Add a Bottle Neck rule for Black:

The user is allowed to place black in a square when that square is the only possible way to make a connection between two areas containing at least one black.

**Comment by Bram28** [comment]
In other words: A cell can be made black when that cell being white would create an Isolated Black contradiction.

**Comment by mmellone** [comment]
Completed.
84696e0cc4d9983f83ab976b235686a3dbed1930
