### ISSUE TITLE
Show Rule Selection

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#51]
When you select transition node, the associated rule (if any) should be clearly marked (e.g. with a green box around it)

**Comment by Bram28** [comment]
I still think a green box around the rule is more clear ... and more consistent with other ways we indicate selections ... the light blue background doesn;t really pop out.

**Comment by samuelyuan** [comment]
I fixed the rule selection by putting a green box around the rule
aca27b904cb799fa35d79af58f7fb6b4610f4dea
