### ISSUE TITLE
Nurikabe: No Number Contradiction Rule

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#66]
This rule should take into account blanks, i.e. there is a contradiction of this kind when there is a region consisting of at least one white, no numbered whites, and zero or more blanks, that is separated from at least one other white (numbered or not).

**Comment by mmellone** [comment]
Fixed.
f64835d5052f6dfcc377cd1bf49e17b883c8bf77

**Comment by Bram28** [comment]
Great!
