### ISSUE TITLE
Nurikabe: Corner Black rule

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#67]
Seems to be broken

**Comment by mmellone** [comment]
Should be fixed. Maybe just some more testing to be sure.

bd46157e2294a42bcc89227b42d886dad15c7a9d

**Comment by Bram28** [comment]
Not there yet ... This should check out:

![corner black bug](https://cloud.githubusercontent.com/assets/2414519/6042891/5e3d3fbe-ac56-11e4-9b9c-18acc5798e26.png)

**Comment by samuelyuan** [comment]
Changed a few lines so that the Corner Black rule works for more cases, like the one pictured above. 
4bae9bfe72c34cc905fbafc7a1d9e98053f19680

**Comment by Bram28** [comment]
Seems to work. Thanks Sam!
