### ISSUE TITLE
Nurikabe: Bottle Neck White

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#68]
We need a Bottle Neck White rule:

A cell is forced to be white if making it black would cause a Region Too Small or No Number contradiction (note that the No Number contradiction rule needs to be extended to allow for blanks).

**Comment by mmellone** [comment]
It's almost done, however it appears there is a bug when extending a white region to a border. The contradiction part of it, so not sure why the rule isn't. I'll try to debug it.

22c40059d3bbae29fd01d210dbd4ba0d44bbefe5

**Comment by mmellone** [comment]
953a281d1f2f81c53239a233a6880bc7e04fb9f0

Fixed the bug. It was actually an error in how the rule checks each contradiction. A combination of two mistakes made it seem that the rule mostly worked when if fact it didn't. Anyway, it appears that this rule is working as it should.

**Comment by Bram28** [comment]
Not quite ...  Given that the No Number Contradiction checks out here ...

![no number ok](https://cloud.githubusercontent.com/assets/2414519/6043111/02c9d2e4-ac58-11e4-93a5-b4e98c71dbb6.png)

the corresponding Bottle Neck White should check out, but it doesn't:

![white bottle neck bug](https://cloud.githubusercontent.com/assets/2414519/6043139/2c7c19e4-ac58-11e4-83ca-c14e6b23677c.png)

And yes, the added white cell leads to a contradiction with the 1, but the White Bottle Neck Rule should not be checking for that; we would use a separate Contradiction rule to point that out.

**Comment by mmellone** [comment]
My mistake, I took the check for the Too Many Spaces contradiction out of the white bottle neck rule.

b1a5a4ec1140163bc9962e6d5eb8911fa2687ade

**Comment by Bram28** [comment]
Ah!  Yes, it should just check for any Too Few Spaces or No Number contradictions.

Bram

**Comment by Bram28** [comment]
Works! Thanks Mitchell!
