### ISSUE TITLE
Nurikabe: Black Between Regions

### ISSUE THREAD

**Issue by AaronPerl** [Bram28/LEGUP#70]
Black between regions rule returns an error unless both white tiles being separated have numbers on them, even if they are part of a region that has a number in it.
![legup_issue_nurikabe](https://cloud.githubusercontent.com/assets/4673310/5968505/24dcb1b0-a7e6-11e4-86ed-068d4886f736.png)

**Comment by mmellone** [comment]
I rewrote this rule using contradictions as we did for black and white bottle neck. It appears to be working now, but lets just test it a little more before we close this issue.

Here is my commit that hopefully solved it:
75677df02678b424567aed5cc83816f6c8a54f66

**Comment by Bram28** [comment]
Seems to work! Thanks!
